config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  post "webhooks/postmark", to: "webhooks#postmark"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :leads, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      patch :mark_as_settled
      patch :mark_as_lost
      patch :mark_as_accepted
    end
  end

  resources :users do
    member do
      patch :toggle_availability
    end
  end

  # static pages

  get 'styleguide', to: 'pages#styleguide'
  get 'simulate_email', to: 'leads#create_from_email'
  patch 'create_simulate_email', to: 'leads#create_new_from_email'
  get '/leads/:id/mark_as_accepted', to: 'leads#mark_as_accepted', as: 'accept_through_email'
  get 'storage', to: 'pages#storage'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :leads
  belongs_to :customer

  validates :name, presence: true, uniqueness: true
  validates :customer, presence: true

end

app/controllers/users_controller.rb
# require '../services/update_lineup.rb'

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :toggle_availability]

  def index
    # @users = User.order(:name)
    if params[:order]
      @users = User.order(params[:order].to_sym)
    else
      @users = User.order(rank: :asc)
    end
    @leads = Lead.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    # find, as above
  end

  def update
    User.create(user_params)
    redirect_to user_path(@user)
  end

  def show
    # find, as above
    @pending_leads = @user.leads.where(status: "pending")
    @ongoing_leads = @user.leads.where(status: "accepted")
    @completed_leads = @user.leads.where(status: ["settled", "lost"])
    @users = User.all
    @leads = Lead.all
  end

  def destroy
    @user.destroy
    redirect_to :back
  end

  def toggle_availability
    if @user.available
      remove_from_lineup(@user)
    else # false to true
      add_to_lineup(@user)
    end
    @user.toggle!(:available)
    redirect_to :back
  end


private

  def add_to_lineup(user)
    AdjustLineupService.new(user).add
  end

  def remove_from_lineup(user)
    AdjustLineupService.new(user).remove
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :manager, :rank, :photo, :available)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def set_users_active_button
    current_page?(users_path) ? "nav-links-active" : ""
  end

  def availability_status_for(user)
    user.available ? "Available" : "Unavailable"
  end
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<!-- User index page -->
<div class="page-fix">
  <div class="main-wrapper bg-light-grey">
    <div class="sidebar">
      <div class="stats-wrapper">
        <div class="bg-grey stats">
          <h2 class="light-font stat-header">Conversion Rate</h2>
          <div class="spinner" id="spinner">
            <div class="rect1"></div>
            <div class="rect2"></div>
            <div class="rect3"></div>
            <div class="rect4"></div>
            <div class="rect5"></div>
          </div>
          <p class="stat-detail stat-number hidden" id="conversion-rate"><%= global_conversion_rate_for(@leads.where(status: "settled"), @leads.where(status: ["settled", "lost"])) %>%</p>
        </div>
      </div>

      <div class="stats-wrapper">
        <div class="bg-grey stats">
          <h2 class="light-font stat-header">Rank #1</h2>
          <h2 class="stat-detail"><%= calculate_ranking(@users).first[:name] %> </h2>
          <!-- INSERT AVATAR HERE -->
          <% top_name = calculate_ranking(@users).first[:name] %>
          <% top_user = User.where(name: top_name) %>
          <%= image_tag top_user.first.photo, class: "center-block avatar-medium" %>
        </div>
      </div>

      <div class="stats-wrapper">
        <div class="bg-grey stats">
          <h2 class="light-font stat-header">Total Leads (this week)</h2>
          <h2 class="stat-detail stat-number"><%= count_leads_since(DateTime.yesterday) %></h2>
        </div>
      </div>

      <div class="stats-wrapper">
        <div class="bg-grey stats">
          <h2 class="light-font stat-header">Avg Response Time (mins):</h2>
          <p class="stat-detail stat-number"><%= (Lead.average(:response_time) / 60).round %></p>
        </div>
      </div>
    </div>

    <div class="main-content">
      <div class="container-fluid">
        <div class="row">
          <!-- div for the add lead button and view window -->
          <div class="col-xs-12">
            <!-- Button to add new lead -->
            <div class="table-wrapper">
              <ul class="list-inline">
                <li>
                  <h1>Sales Team Management</h1>
                </li>
                <li>
                  <%= link_to "Add Salesperson", new_user_path, class: "btn btn-primary add-lead-btn", id: "bottom-button-margin" %>
                </li>
              </ul>
            <div class="next-lead-box">
              <%= image_tag("blue-icon.png", size: "30x18", alt: "Mail Icon") %>
              <!--
              Placing conditional here to fix site logic.
              Entire site would crash when no users were on duty.
              Will be expanding on this concept with an "unassigned user" to collect
              all unassigned leads due to all team offline.
              -->
              <% if Lineup.first.lineup.empty? %>
                <h3><b>Warning: No staff on duty to receive leads</b></h3>
              <% else %>
                <h3>The next lead will be forwarded to: <b><%= Lineup.first.lineup.first.name %></b></h3>
              <% end %>
            </div>
              <!-- Main table of employees -->
              <div class="scroll-me">
                <table class="table table-striped" id="TableSort" style="width:100%">

                  <tr class="bg-grey light-font" id="table-header-green">
                    <th class="user-th rank-width"> <%= link_to users_path(order: "rank") do %>Rank<i class="fa fa-sort light-font" aria-hidden="true"></i><% end %></th>

                    <th class="user-th name-width"><%= link_to users_path(order: "name") do %>Salesperson<i class="fa fa-sort light-font" aria-hidden="true"></i><% end %></th>

                    <th class="user-th email-width"><%= link_to users_path(order: "email") do %>Email<i class="fa fa-sort light-font" aria-hidden="true"></i><% end %></th>

                    <th class="user-th conversion-width">Conversion %</th>
                    <th class="user-th response-width">Avg Response Time</th>
                    <th class="user-th avail-width">Availability</th>
                    <th class="user-th delete-width">Delete</th>
                  </tr>

                  <% @users.each do |user| %>
                    <tr class="user-tr">
                      <td class="user-td" id="rank-align"><%= user.rank %></td>
                      <td class="user-td"><%= link_to user.name, user_path(user) %></td>
                      <td class="user-td"><%= user.email %></td>
                      <td class="user-td" id="rank-align"><%= conversion_rate_for(user) %> %</td>
                      <td class="user-td" id="rank-align"><%= user.leads.average(:response_time) ? (user.leads.average(:response_time) / 60).round : "n/a" %> mins</td>
                      <td class="user-td">

                        <% if user.available %>
                          <%= link_to toggle_availability_user_path(user), method: :patch do %>
                            <label class="switch2">
                              <input type="checkbox" checked>
                              <div class="slider2"><div class="ontext2">Available</div></div>
                            </label>
                          <% end %>
                        <% else %>
                          <%= link_to toggle_availability_user_path(user), method: :patch do %>
                            <label class="switch2">
                              <input type="checkbox">
                              <div class="slider2"><div class="offtext2">Off Duty</div></div>
                            </label>
                          <% end %>
                        <% end %>
                        </div>
                      </td>

                      <td class="pad-right-plz">
                        <%= link_to user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user?" } do %>
                          <i class="fa fa-times" aria-hidden="true"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="main-wrapper bg-light-grey">
  <div class="sidebar">
    <div class="avatar-wrapper">
      <%= image_tag @user.photo, class: "avatar-large" %>
      <h3 class="light-font"><%= @user.name %></h3>
      <!-- New toggle slide -->
      <% if @user.available %>
        <%= link_to toggle_availability_user_path(@user), method: :patch do %>
          <label class="switch">
            <input type="checkbox" checked>
            <div class="slider"><div class="ontext">AVAILABLE</div></div>
          </label>
        <% end %>
      <% else %>
        <%= link_to toggle_availability_user_path(@user), method: :patch do %>
          <label class="switch">
            <input type="checkbox">
            <div class="slider"><div class="offtext">OFF DUTY</div></div>
          </label>
        <% end %>
      <% end %>
    </div>

    <div class="stats-wrapper">
      <div class="bg-grey stats">
        <h2 class="light-font stat-header">Conversion Rate</h2>
        <div class="spinner" id="spinner">
            <div class="rect1"></div>
            <div class="rect2"></div>
            <div class="rect3"></div>
            <div class="rect4"></div>
            <div class="rect5"></div>
          </div>
          <p class="stat-detail stat-number hidden" id="conversion-rate"><%= conversion_rate_for(@user) %> %</p>
      </div>
    </div>

    <div class="stats-wrapper">
      <div class="bg-grey stats">
        <h2 class="light-font stat-header">Ranking</h2>
          <p class="stat-detail stat-number"><%= find_user_ranking(@user, @users) %> / <%= @users.count %></p>
      </div>
    </div>

    <div class="stats-wrapper">
      <div class="bg-grey stats">
        <h2 class="light-font stat-header">Avg Response Time (mins):</h2>
          <p class="stat-detail stat-number"><%= @user.leads.average(:response_time) ? (@user.leads.average(:response_time) / 60).round : "n/a" %></p>
      </div>
    </div>
  </div>
 <!-- PENDING LEADS TABLE -->
  <div class="col-sm-12">
    <div class="table-wrapper">
      <h2> Pending Leads: </h2>
      <div class="scroll-me2">
        <table class="user-table table-striped" style="width:100%">
        <tr class="table-header bg-grey light-font" id="table-header-green">
          <th class="user-th"></th>
          <th class="user-th">Lead ID:</th>
          <th class="user-th">Status:</th>
          <th class="user-th">Received:</th>
        </tr>
        <% if @pending_leads.any? %>
        <% @pending_leads.each do |lead| %>
        <tr class="user-tr">
          <td class="user-td"><%= link_to "Accept", mark_as_accepted_lead_path(lead), method: :patch, class: "btn btn-primary table-button" %></td>
          <td class="user-td">000<%= lead.id %></td>
          <td class="user-td"><%= lead.status.capitalize %></td>
          <td class="user-td"><%= lead.created_at.strftime("%d/%m/%y at %I:%M%p") %> (<%= time_ago_in_words(lead.created_at) %> ago)</td>
        </tr>
        <% end %>
        </table>
        <% else %>
          </table>
          <div class="no-pending-details">No pending leads to display</div>
        <% end %>
      </div><BR><BR>

 <!-- WIP LEADS TABLE -->

    <h2> Work In Progress: </h2>
    <div class="scroll-me2">
      <table class="user-table table table-striped" style="width:100%">
      <tr class="table-header bg-grey light-font" id="table-header-grey">
        <th class="user-th lead-th">Lead ID:</th>
        <th class="user-th">Name:</th>
        <th class="user-th">Email:</th>
        <th class="user-th phone-th">Phone:</th>
        <th class="user-th source-th">Source:</th>
        <th class="user-th">Generated:</th>
        <th class="user-th outcome-th">Outcome:</th>
      </tr>
      <% if @ongoing_leads.any? %>
      <% @ongoing_leads.each do |lead| %>
      <tr class="user-tr">
        <td class="user-td">000<%= lead.id %></td>
        <td class="user-td"><%= lead.name %></td>
        <td class="user-td"><%= lead.email %></td>
        <td class="user-td"><%= lead.phone %></td>
        <td class="user-td"><%= lead.source %></td>
        <td class="user-td"><%= lead.created_at.strftime("%d/%m/%y at %I:%M%p") %></td>
        <td class="user-td">
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle table-button" type="button" data-toggle="dropdown">Options
            <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li><%= link_to "Settle Lead", mark_as_settled_lead_path(lead), method: :patch, class: "table-dropdown" %></li>
              <li><%= link_to "Mark as Lost", mark_as_lost_lead_path(lead), method: :patch, class: "table-dropdown" %></li>
            </ul>
          </div>
        </td>
      </tr>
      <% end %>
      </table>
      <% else %>
        </table>
        <div class="no-details">No ongoing leads to display</div>
      <% end %>
    </div>

    <!-- PREVIOUS LEADS TABLE -->
    <h2> Previous Leads: </h2>
    <!-- Insert conditional for empty table check here -->
    <div class="scroll-me2">
      <table class="user-table table table-striped" style="width:100%">
        <tr class="table-header bg-grey light-font" id="table-header-grey">
          <th class="user-th name-th">Name:</th>
          <th class="user-th email-th">Email:</th>
          <th class="user-th phone-th">Phone:</th>
          <th class="user-th source-th">Source:</th>
          <th class="user-th">Generated:</th>
          <th class="user-th result-th">Result:</th>
        </tr>
        <% if @completed_leads.any? %>
          <% @completed_leads.each do |lead| %>
            <tr class="user-tr">
              <td class="user-td"><%= lead.name %></td>
              <td class="user-td"><%= lead.email %></td>
              <td class="user-td"><%= lead.phone %></td>
              <td class="user-td"><%= lead.source %></td>
              <td class="user-td"><%= lead.created_at.strftime("%d/%m/%y at %I:%M%p") %></td>
              <td class="user-td"><%= lead.status.capitalize %></td>
            </tr>
          <% end %>
        </table>
        <% else %>
          </table>
          <div class="no-details">No lead history to display</div>
        <% end %>
    </div>
  </div>
</div>
</div>

app/views/users/toggle_availability.html.erb
<h1>Users#toggle_availability</h1>
<p>Find me in app/views/users/toggle_availability.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>