config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  post "webhooks/postmark", to: "webhooks#postmark"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :leads, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      patch :mark_as_settled
      patch :mark_as_lost
      patch :mark_as_accepted
    end
  end

  resources :users do
    member do
      patch :toggle_availability
    end
  end

  # static pages

  get 'styleguide', to: 'pages#styleguide'
  get 'simulate_email', to: 'leads#create_from_email'
  patch 'create_simulate_email', to: 'leads#create_new_from_email'
  get '/leads/:id/mark_as_accepted', to: 'leads#mark_as_accepted', as: 'accept_through_email'
  get 'storage', to: 'pages#storage'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <p> Copyright LeadMailer 2017 </p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <div class="navbar-wagon-left">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <ul class="list-inline navbar-buttons">
      <li><%= link_to "STAFF", users_path, class: "nav-links #{set_users_active_button}", id: "staff-link" %> </li>
      <li><%= link_to "LEADS", leads_path, class: "nav-links #{set_leads_active_button}", id: "lead-link" %> </li>
      <!-- Need to add a 3rd hidden "storage" tab for when no users available (CH) -->
      <li><%= link_to "STORAGE", storage_path, class: "nav-links #", id: "storage-links" %></li>

    </ul>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
    <h3 id="welcome-message"> <%= greet %> <%= current_user.name.split.first %>!</h3>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <%= image_tag current_user.photo, class: "avatar-small dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to current_user do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Export Leads"), "/leads.csv", class: "navbar-wagon-item btn btn-primary", id: "nav-button" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <!-- This needs updating once site is 100% responsive (CH) -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">UPDATE ME #1</a></li>
        <li><a href="#">UPDATE ME #2</a></li>
        <li><a href="#">UPDATE ME #3</a></li>
      </ul>
    </div>
  </div>
</div>