config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  post "webhooks/postmark", to: "webhooks#postmark"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :leads, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      patch :mark_as_settled
      patch :mark_as_lost
      patch :mark_as_accepted
    end
  end

  resources :users do
    member do
      patch :toggle_availability
    end
  end

  # static pages

  get 'styleguide', to: 'pages#styleguide'
  get 'simulate_email', to: 'leads#create_from_email'
  patch 'create_simulate_email', to: 'leads#create_new_from_email'
  get '/leads/:id/mark_as_accepted', to: 'leads#mark_as_accepted', as: 'accept_through_email'
  get 'storage', to: 'pages#storage'

end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :customer
  belongs_to :user, optional: true

  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A.*@.*\.\S*\z/ }
  validates :user, presence: true
  validates :phone, presence: true
  validates :source, presence: true
  validates :html, presence: true
  validates :customer, presence: true
  validates :status, inclusion: { in: ["pending","accepted","settled","lost"], allow_nil: false }

  def self.to_csv
    attributes = %w{name email received_at accepted_at user status source response_time created_at updated_at phone }
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |lead|
        hash = lead.attributes
        hash["user"] = lead.user.name
        csv << hash.values_at(*attributes)
      end
    end
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:edit, :update, :destroy, :mark_as_settled, :mark_as_lost, :mark_as_accepted]
  # rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index

    order_by = params[:order]

    if order_by
      order_by = "users.name" if order_by == "salesperson"
      @leads = Lead.includes(:user).order(order_by)
    else
      @leads = Lead.includes(:user).order(received_at: :desc)
    end
    @users = User.all

    respond_to do |format|
      format.html
      format.csv { send_data @leads.to_csv, filename: "leadmailer-leads-#{Date.today}.csv" }
    end

    @leads = Lead.all
    @leads = Lead.paginate(page: params[:page], per_page: 10)
  end


  def new
    @lead = Lead.new
  end

  def create
    @users = User.all
    @lead = Lead.new(lead_params)
    @lead.received_at = DateTime.now()
    @lead.status = "pending"
    @lead.html = "This lead wasn't generated from an email."
    @lead.source = @lead.source.strip
    if @lead.save
      UserMailer.newlead(@lead).deliver_now
      store_user_rankings(@users)
      redirect_to leads_path
    else
      render :new
    end
  end


  def edit
  end


  def update
    @users = User.all
    @lead.update(lead_params)
    if @lead.save
      store_user_rankings(@users)
      redirect_to leads_path
      # redirect_to :back
    else
      render :new
    end
  end

  def destroy
    @users = User.all
    @lead.destroy
    store_user_rankings(@users)
    redirect_to leads_path
  end




  # beyond CRUD - User Actions:

  def mark_as_accepted
    @lead.accepted_at = DateTime.now
    @lead.response_time = @lead.accepted_at - @lead.created_at
    @lead.status = "accepted"
    @lead.save
    @users = User.all
    store_user_rankings(@users)
    UserMailer.forward(@lead).deliver_now
    if request.referer.nil?
      redirect_to user_path(@lead.user)
    else
      redirect_to :back
    end
  end

  def mark_as_settled
    @lead.status = "settled"
    @lead.save
    @users = User.all
    store_user_rankings(@users)
    redirect_to :back
  end

  def mark_as_lost
    @lead.status = "lost"
    @lead.save
    @users = User.all
    store_user_rankings(@users)
    redirect_to :back
  end

  # Simulate Incoming Email:

  def create_from_email
    @lead = Lead.new
  end

  def create_new_from_email
    @lead = Lead.new(lead_params)
    @lead.received_at = DateTime.now()
    @lead.status = "pending"
    Lineup.build(User.all)
    @lead.user_id = assign_user(@lead.email).id
    @lead.save
    redirect_to leads_path
  end

  def assign_user(input_email)
    if Lead.where(email: input_email).last
      Lead.where(email: input_email).last.user
    else
      lineup = Lineup.first
      assignment = lineup.lineup[0]
      lineup.bump
      assignment
    end
  end




  # Stat Calculations:

  def store_user_rankings(users)
    # users -> User.all -> this is all you need to access this method
    # calculate rankings, result -> [{name: biz, conversion: 23, ranking: 1}, ...]
    rankings = calculate_ranking(users)
    # store ranking to user instance
    users.each do |user|
      user.rank = rankings.find_index { |salesperson| salesperson[:name] == user.name } + 1
      user.save
    end
  end

  def calculate_ranking(users)
    ranking = []
    users.each do |user|
      ranking << {name: user.name, conversion: conversion_rate_for(user), rank: nil}
    end
    ranking.sort_by { |hsh| hsh[:conversion] }.reverse
    # result -> [{name: biz, conversion: 23, ranking: nil}, {}, {}]
    # ranking.map.with_index { |hsh, i| { name: hsh[:name], conversion: hsh[:conversion], rank: (i + 1) } }
  end

  def conversion_rate_for(user)
    lead_conversion_count = user.leads.where(status: "settled").count.to_f
    total_leads_count = user.leads.where(status: ["settled", "lost"]).count.to_f
    if total_leads_count != 0.0
      return (lead_conversion_count / total_leads_count * 100).round(2)
    else
      return 0.0
    end
  end

private

  def lead_params
    params.require(:lead).permit(:name, :email, :received_at, :accepted_at, :status, :source, :user_id, :phone)
  end

  def set_lead
    @lead = Lead.find(params[:id])
  end
end

app/helpers/leads_helper.rb
module LeadsHelper
  def set_leads_active_button
    current_page?(leads_path) ? "nav-links-active" : ""
  end

  def count_leads_since(time_period)
    Lead.where("created_at > ?", time_period).count
  end

  def global_conversion_rate_for(lead_selection, total_leads)
    return (lead_selection.count.to_f / total_leads.count * 100).round(2)
  end

  # ranking calculations:
  def calculate_ranking(users)
    ranking = []
    users.each do |user|
      ranking << {name: user.name, conversion: conversion_rate_for(user), rank: nil}
#     ranking << {name: user.name, conversion: conversion_rate_for(user), photo: user.photo}
    end
    ranking.sort_by { |hsh| hsh[:conversion] }.reverse
    # result -> [{name: biz, conversion: 23, ranking: nil}, {}, {}]
    # ranking.map.with_index { |hsh, i| { name: hsh[:name], conversion: hsh[:conversion], rank: (i + 1) } }
  end

  def conversion_rate_for(user)
    lead_conversion_count = user.leads.where(status: "settled").count.to_f
    total_leads_count = user.leads.where(status: ["settled", "lost"]).count.to_f
    if total_leads_count != 0.0
      return (lead_conversion_count / total_leads_count * 100).round(2)
    else
      return 0.0
    end
  end

  def find_user_ranking(user, users)
    ranking_matrix = calculate_ranking(users)
    ranking = ranking_matrix.find_index { |salesperson| salesperson[:name] == user.name } + 1
  end

  def store_user_rankings(users)
    # users -> User.all -> this is all you need to access this method
    # calculate rankings, result -> [{name: biz, conversion: 23, ranking: 1}, ...]
    rankings = calculate_ranking(users)
    # store ranking to user instance
    users.each do |user|
      user.rank = rankings.find_index { |salesperson| salesperson[:name] == user.name } + 1
    end
  end
end

app/views/leads/create_from_email.html.erb
<h1>Similate Lead being created from incoming email</h1>


<%= simple_form_for @lead, :url => create_simulate_email_path, :method => :patch do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :source %>
  <%= f.button :submit %>
<% end %>

app/views/leads/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Edit Lead Details...</h1>
      <div class="bg-light-grey lead-form">
        <%= simple_form_for @lead do |f| %>
          <%= f.input :name %>
          <%= f.input :email %>
          <%= f.input :source %>
          <%= f.association :user %>
          <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/leads/index.html.erb
<!-- LEADS INDEX PAGE -->
<div class="main-wrapper bg-light-grey">
  <div class="sidebar">
    <div class="stats-wrapper">
      <div class="bg-grey stats">
        <h2 class="light-font stat-header">Conversion Rate</h2>
        <div class="spinner" id="spinner">
            <div class="rect1"></div>
            <div class="rect2"></div>
            <div class="rect3"></div>
            <div class="rect4"></div>
            <div class="rect5"></div>
          </div>
        <p class="stat-detail stat-number hidden" id="conversion-rate"><%= global_conversion_rate_for(@leads.where(status: "settled"), @leads.where(status: ["settled", "lost"])) %>%</p>
      </div>
    </div>

    <div class="stats-wrapper">
      <div class="bg-grey stats">
        <h2 class="light-font stat-header">Rank #1</h2>
        <h2 class="stat-detail"><%= calculate_ranking(@users).first[:name] %> </h2>
        <!-- INSERT AVATAR HERE -->
        <% top_name = calculate_ranking(@users).first[:name] %>
        <% top_user = User.where(name: top_name) %>
        <%= image_tag top_user.first.photo, class: "center-block avatar-medium" %>
      </div>
    </div>

    <div class="stats-wrapper">
      <div class="bg-grey stats">
        <h2 class="light-font stat-header">Total Leads (this week)</h2>
        <h2 class="stat-detail stat-number"><%= count_leads_since(DateTime.yesterday) %></h2>
      </div>
    </div>

    <div class="stats-wrapper">
      <div class="bg-grey stats">
        <h2 class="light-font stat-header">Avg Response Time (mins):</h2>
        <p class="stat-detail stat-number"><%= (Lead.average(:response_time) / 60).round %></p>
      </div>
    </div>
</div>

<div class="main-content">
  <div class="container-fluid">
    <div class="row">
    <div class="col-xs-12">
      <div class="table-wrapper">
      <ul class="list-inline">
      <li><h1>Leads Status</h1></li>
      <!-- Manually Create Lead -->
      <li><%= link_to "Add Lead", new_lead_path, class: "btn btn-primary add-lead-btn", id: "bottom-button-margin" %></li>
      <div class="next-lead-box">
      <%= image_tag("blue-icon.png", size: "30x18", alt: "Mail Icon") %>

      <!-- Need to add conditional here to prevent site crash when no users -->
        <% if Lineup.first.lineup.empty? %>
          <h3><b>Warning: No staff on duty to receive leads</b></h3>
        <% else %>
          <h3>The next lead will be forwarded to: <b><%= Lineup.first.lineup.first.name %></b></h3>
        <% end %>


       </div>
          <div class="scroll-me">
          <%= will_paginate %>
            <table class="table table-fit table-striped" style="width:100%">

          <tr class="bg-grey light-font table-font" id="table-header-grey">
            <th class="user-th"><%= link_to leads_path(order: "received_at") do %>Received<i class="fa fa-sort light-font" aria-hidden="true"></i><% end %></th>

            <th class="user-th status-width"><%= link_to leads_path(order: "status") do %>Status<i class="fa fa-sort light-font" aria-hidden="true"></i><% end %></th>

            <th class="user-th sales-width"><%= link_to leads_path(order: "salesperson") do %>Salesperson<i class="fa fa-sort light-font" aria-hidden="true"></i><% end %></th>

            <th class="user-th"><%= link_to leads_path(order: "name") do %>Lead Name<i class="fa fa-sort light-font" aria-hidden="true"></i><% end %></th>

            <th class="user-th"><%= link_to leads_path(order: "email") do %>Lead Email<i class="fa fa-sort light-font" aria-hidden="true"></i><% end %></th>

            <th class="user-th"><%= link_to leads_path(order: "phone") do %>Lead Phone<% end %></th>

            <th class="user-th source-width"><%= link_to leads_path(order: "source") do %>Source<i class="fa fa-sort light-font" aria-hidden="true"></i><% end %></th>

            <th class="user-th options-width"></th>
            <th class="user-th"></th>
          </tr>

          <% @leads.each do |lead| %>
          <tr class="user-tr">
            <td class="user-td"><%= lead.created_at.strftime(" %d/%m/%y at %I:%M%p") %></td>
            <td class="user-td">
            <% if lead.status == "settled" %>
              <div id="status-green"> <%= lead.status.capitalize %></td>
              </div>
            <% elsif lead.status == "pending" %>
              <div id="status-yellow"> <%= lead.status.capitalize %></td>
              </div>
            <% elsif lead.status == "accepted" %>
              <div id="status-blue"> <%= lead.status.capitalize %></td>
              </div>
            <% else lead.status == "lost" %>
              <div id="status-red"> <%= lead.status.capitalize %></td>
              </div>
            <% end %>
            <td class="user-td"><%= link_to lead.user.name, user_path(lead.user) %></td>
            <td class="user-td"><%= lead.name %></td>
            <td class="user-td"><%= lead.email %></td>
            <td class="user-td"><%= lead.phone %></td>
            <td class="user-td"><%= lead.source %></td>
            <td class="user-td">
            <div class="drpdwn">
                <div class="dropdown">
                  <button class="btn btn-primary dropdown-toggle table-button" type="button" data-toggle="dropdown">Options
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Accept Lead", mark_as_accepted_lead_path(lead), method: :patch, class: "table-dropdown" %></li>
                    <li><%= link_to "Settle Lead", mark_as_settled_lead_path(lead), method: :patch, class: "table-dropdown" %></li>
                    <li><%= link_to "Mark as Lost", mark_as_lost_lead_path(lead), method: :patch, class: "table-dropdown" %></li>
                  </ul>
                </div>
            </div>
            </td>
            <td class="user-td">
              <%= link_to "Edit", edit_lead_path(lead), class: "btn btn-primary table-button" %>
              <%= link_to lead_path(lead), method: :delete, class: "x-margin", data: { confirm: "Are you sure you want to Delete this lead?" } do %>
              <i class="fa fa-times" aria-hidden="true"></i>
              <% end %>
              </td>
          </tr>
          <% end %>
          </table>
          <%= will_paginate %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/leads/new.html.erb
<!-- @lead = Lead.new -->
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h1>Add a Lead...</h1>
      <div class="bg-light-grey lead-form">
        <%= simple_form_for @lead do |f| %>
          <%= f.input :name %>
          <%= f.input :email %>
          <%= f.input :phone %>
          <%= f.input :source %>
          <%= f.association :user %>
          <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>